# FILE: backend/config.py
from __future__ import annotations

DB_PATH = "onion_travel_feed.db"

HOST = "127.0.0.1"
PORT = 8765

SCAN_INTERVAL_SECONDS = 30 * 60
ITEM_TTL_DAYS = 7

REQUEST_TIMEOUT_SECONDS = 40
USER_AGENT = "OnionTravelFeed/0.1"

RSS_SOURCES = [
    # GLOBAL CLASSICAL MEDIA (HIGH SIGNAL)
    {"name": "Bachtrack", "url": "https://bachtrack.com/rss", "official": False},
    {"name": "Classic FM News", "url": "https://www.classicfm.com/news/rss.xml", "official": False},
    {"name": "Gramophone", "url": "https://www.gramophone.co.uk/rss.xml", "official": False},
    {"name": "Limelight Arts", "url": "https://limelight-arts.com.au/feed/", "official": False},
    {"name": "ABC Arts", "url": "https://www.abc.net.au/news/feed/51120/rss.xml", "official": False},
    {"name": "Guardian Classical", "url": "https://www.theguardian.com/music/classicalmusic/rss", "official": False},
    {"name": "NPR Music", "url": "https://www.npr.org/rss/rss.php?id=1039", "official": False},

    # UK MAJOR INSTITUTIONS
    {"name": "Royal Opera House", "url": "https://www.roh.org.uk/rss/news", "official": True},
    {"name": "London Symphony Orchestra", "url": "https://lso.co.uk/feed/", "official": True},
    {"name": "BBC Proms", "url": "https://www.bbc.co.uk/programmes/b007v097/episodes/player.rss", "official": True},
    {"name": "Royal Philharmonic Orchestra", "url": "https://www.rpo.co.uk/news/rss", "official": True},
    {"name": "Philharmonia Orchestra UK", "url": "https://philharmonia.co.uk/feed/", "official": True},

    # USA MAJOR INSTITUTIONS
    {"name": "New York Philharmonic", "url": "https://nyphil.org/rss", "official": True},
    {"name": "Los Angeles Philharmonic", "url": "https://www.laphil.com/rss", "official": True},
    {"name": "Chicago Symphony Orchestra", "url": "https://cso.org/rss", "official": True},
    {"name": "San Francisco Symphony", "url": "https://www.sfsymphony.org/rss", "official": True},
    {"name": "Metropolitan Opera", "url": "https://www.metopera.org/rss/news", "official": True},

    # AUSTRALIA / NEW ZEALAND (DESTINATION REGION)
    {"name": "NZSO", "url": "https://www.nzso.co.nz/feed/", "official": True},
    {"name": "Auckland Philharmonia", "url": "https://www.aucklandphil.nz/feed/", "official": True},
    {"name": "Sydney Symphony", "url": "https://www.sydneysymphony.com/rss", "official": True},
    {"name": "Melbourne Symphony", "url": "https://www.mso.com.au/feed/", "official": True},
    {"name": "Opera Australia", "url": "https://www.opera.org.au/feed/", "official": True},
    {"name": "Queensland Symphony", "url": "https://www.qso.com.au/feed/", "official": True},

    # EVENTS / AGGREGATORS
    {"name": "Eventfinda NZ", "url": "https://www.eventfinda.co.nz/rss/events", "official": False},

    # LOW PRIORITY (OPTIONAL SIGNAL)
    {"name": "Pitchfork News", "url": "https://pitchfork.com/rss/news/", "official": False},
    {"name": "Billboard", "url": "https://www.billboard.com/feed/", "official": False},
]

CLASSICAL_TERMS = [
    "orchestra",
    "philharmonic",
    "symphony",
    "opera",
    "ballet",
    "chamber",
    "ensemble",
    "quartet",
    "quintet",
    "trio",
    "duo",
    "soloist",
    "violin",
    "violinist",
    "viola",
    "violist",
    "cello",
    "cellist",
    "double bass",
    "bassist",
    "harp",
    "harpist",
    "flute",
    "flautist",
    "oboe",
    "oboist",
    "clarinet",
    "clarinettist",
    "clarinetist",
    "bassoon",
    "bassoonist",
    "horn",
    "hornist",
    "trumpet",
    "trumpeter",
    "trombone",
    "trombonist",
    "tuba",
    "tubist",
    "percussion",
    "percussionist",
    "timpanist",
    "piano",
    "pianist",
    "harpsichord",
    "harpsichordist",
    "organ",
    "organist",
    "soprano",
    "mezzo",
    "mezzo-soprano",
    "alto",
    "tenor",
    "baritone",
    "bass",
    "conductor",
    "maestro",
    "composer",
    "recital",
    "concerto",
    "sonata",
    "festival",
    "residency",
    "residency artist",
    "artist in residence",
]

AU_NZ_LOCATION_TERMS = [
    "australia",
    "new zealand",
    "anzac",
    "auckland",
    "wellington",
    "christchurch",
    "dunedin",
    "hamilton",
    "tauranga",
    "queenstown",
    "nelson",
    "palmerston north",
    "rotorua",
    "new plymouth",
    "napier",
    "whangarei",
    "invercargill",
    "gisborne",
    "hobart",
    "sydney",
    "melbourne",
    "brisbane",
    "perth",
    "adelaide",
    "canberra",
    "gold coast",
    "newcastle",
    "wollongong",
    "geelong",
    "darwin",
    "sunshine coast",
    "cairns",
    "townsville",
    "tasmania",
    "victoria",
    "queensland",
    "new south wales",
    "western australia",
    "south australia",
    "northern territory",
    "australian",
    "kiwi",
    "nz",
    "aotearoa",
]

CONFIRMED_TERMS = [
    "announced",
    "tickets on sale",
    "season",
    "performance",
    "cast",
    "programme",
    "program",
    "appearing",
    "appearance",
    "tour",
    "touring",
    "debut",
    "residency",
    "opening night",
    "guest artist",
    "guest conductor",
    "guest soloist",
    "conducted by",
    "comes to",
    "coming to",
    "heads to",
    "heading to",
    "returns to",
    "set for",
    "scheduled for",
    "booked for",
    "confirmed for",
]

UNCONFIRMED_TERMS = [
    "rumour",
    "rumor",
    "reportedly",
    "expected",
    "planned",
    "planning",
    "possible",
    "may appear",
    "could appear",
    "might",
    "mooted",
    "speculation",
    "speculated",
    "tipped for",
    "in talks",
    "linked with",
    "set to",
    "likely to",
]

MOVEMENT_TERMS = [
    "tour",
    "tours",
    "touring",
    "visit",
    "visits",
    "visiting",
    "travels to",
    "travel to",
    "coming to",
    "comes to",
    "headed to",
    "heading to",
    "heads to",
    "returns to",
    "returning to",
    "appearing",
    "appear",
    "appearance",
    "performing in",
    "performs in",
    "perform in",
    "guest artist",
    "guest conductor",
    "guest soloist",
    "guest appearance",
    "artist in residence",
    "residency",
    "resident artist",
    "debut in",
    "debut at",
    "set for",
    "scheduled for",
    "booked for",
    "booked to perform",
    "line-up",
    "lineup",
    "festival appearance",
    "season opener",
    "opening night",
    "rumour",
    "rumor",
    "reportedly",
    "expected",
    "planned",
    "planning",
    "possible",
    "in talks",
    "linked with",
]

ARTIST_WATCH_TERMS = [
    "hilary hahn",
    "lang lang",
    "yuja wang",
    "itzhak perlman",
    "anne-sophie mutter",
    "joshua bell",
    "daniil trifonov",
    "martha argerich",
    "yunchan lim",
    "sheku kanneh-mason",
    "nicola benedetti",
    "maxim vengerov",
    "jakub hrusa",
    "gustavo dudamel",
    "antonio pappano",
    "simon rattle",
    "andris nelsons",
    "klaus makela",
    "marin alsop",
    "jonathan cohen",
    "barbara hannigan",
    "vikingur olafsson",
    "rachel willis-sorensen",
    "juan diego florez",
    "lise davidsen",
]

TARGET_YEAR_TERMS = []