# FILE: backend/config.py
from __future__ import annotations

DB_PATH = "onion_travel_feed.db"

HOST = "127.0.0.1"
PORT = 8765

SCAN_INTERVAL_SECONDS = 30 * 60
ITEM_TTL_DAYS = 7

REQUEST_TIMEOUT_SECONDS = 40
USER_AGENT = "OnionTravelFeed/0.1"

RSS_SOURCES = [
    {"name": "Guardian Music", "url": "https://www.theguardian.com/music/rss"},
    {"name": "BBC Music", "url": "http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml"},
]

CLASSICAL_TERMS = [
    "orchestra",
    "philharmonic",
    "symphony",
    "opera",
    "ballet",
    "chamber",
    "ensemble",
    "quartet",
    "quintet",
    "trio",
    "duo",
    "soloist",
    "violin",
    "violinist",
    "viola",
    "violist",
    "cello",
    "cellist",
    "double bass",
    "bassist",
    "harp",
    "harpist",
    "flute",
    "flautist",
    "oboe",
    "oboist",
    "clarinet",
    "clarinettist",
    "clarinetist",
    "bassoon",
    "bassoonist",
    "horn",
    "hornist",
    "trumpet",
    "trumpeter",
    "trombone",
    "trombonist",
    "tuba",
    "tubist",
    "percussion",
    "percussionist",
    "timpanist",
    "piano",
    "pianist",
    "harpsichord",
    "harpsichordist",
    "organ",
    "organist",
    "soprano",
    "mezzo",
    "mezzo-soprano",
    "alto",
    "tenor",
    "baritone",
    "bass",
    "conductor",
    "maestro",
    "composer",
    "recital",
    "concerto",
    "sonata",
    "festival",
    "residency",
    "residency artist",
    "artist in residence",
]

AU_NZ_LOCATION_TERMS = [
    "australia",
    "new zealand",
    "anzac",
    "auckland",
    "wellington",
    "christchurch",
    "dunedin",
    "hamilton",
    "tauranga",
    "queenstown",
    "nelson",
    "palmerston north",
    "rotorua",
    "new plymouth",
    "napier",
    "whangarei",
    "invercargill",
    "gisborne",
    "hobart",
    "sydney",
    "melbourne",
    "brisbane",
    "perth",
    "adelaide",
    "canberra",
    "gold coast",
    "newcastle",
    "wollongong",
    "geelong",
    "darwin",
    "sunshine coast",
    "cairns",
    "townsville",
    "tasmania",
    "victoria",
    "queensland",
    "new south wales",
    "western australia",
    "south australia",
    "northern territory",
    "australian",
    "kiwi",
    "nz",
    "aotearoa",
]

CONFIRMED_TERMS = [
    "announced",
    "tickets on sale",
    "season",
    "performance",
    "cast",
    "programme",
    "program",
    "appearing",
    "appearance",
    "tour",
    "touring",
    "debut",
    "residency",
    "opening night",
    "guest artist",
    "guest conductor",
    "guest soloist",
    "conducted by",
    "comes to",
    "coming to",
    "heads to",
    "heading to",
    "returns to",
    "set for",
    "scheduled for",
    "booked for",
    "confirmed for",
]

UNCONFIRMED_TERMS = [
    "rumour",
    "rumor",
    "reportedly",
    "expected",
    "planned",
    "planning",
    "possible",
    "may appear",
    "could appear",
    "might",
    "mooted",
    "speculation",
    "speculated",
    "tipped for",
    "in talks",
    "linked with",
    "set to",
    "likely to",
]

MOVEMENT_TERMS = [
    "tour",
    "tours",
    "touring",
    "visit",
    "visits",
    "visiting",
    "travels to",
    "travel to",
    "coming to",
    "comes to",
    "headed to",
    "heading to",
    "heads to",
    "returns to",
    "returning to",
    "appearing",
    "appear",
    "appearance",
    "performing in",
    "performs in",
    "perform in",
    "guest artist",
    "guest conductor",
    "guest soloist",
    "guest appearance",
    "artist in residence",
    "residency",
    "resident artist",
    "debut in",
    "debut at",
    "set for",
    "scheduled for",
    "booked for",
    "booked to perform",
    "line-up",
    "lineup",
    "festival appearance",
    "season opener",
    "opening night",
    "rumour",
    "rumor",
    "reportedly",
    "expected",
    "planned",
    "planning",
    "possible",
    "in talks",
    "linked with",
]

ARTIST_WATCH_TERMS = [
    "hilary hahn",
    "lang lang",
    "yuja wang",
    "itzhak perlman",
    "anne-sophie mutter",
    "joshua bell",
    "daniil trifonov",
    "martha argerich",
    "yunchan lim",
    "sheku kanneh-mason",
    "nicola benedetti",
    "maxim vengerov",
    "jakub hrusa",
    "gustavo dudamel",
    "antonio pappano",
    "simon rattle",
    "andris nelsons",
    "klaus makela",
    "marin alsop",
    "jonathan cohen",
    "barbara hannigan",
    "vikingur olafsson",
    "rachel willis-sorensen",
    "juan diego florez",
    "lise davidsen",
]

TARGET_YEAR_TERMS = []
